sonar.projectKey=LeticiaResende23_Trabalho-Individual-GCES
sonar.organization=leticiaresende23
sonar.projectName=Trabalho Individual GCES
sonar.sourceEncoding=UTF-8

sonar.sources=server,game/src
sonar.tests=server/__tests__
sonar.exclusions=node_modules/**,coverage/**,coverage-sonar/**
sonar.coverage.exclusions=game/**,server/server.js,server/db.js,server/__tests__/**
sonar.javascript.lcov.reportPaths=coverage-sonar/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
